# modified from verbs.xml in Joshua Adams' "Conjugar":
# https://github.com/vermont42/Conjugar

regulars = {
	'absorber':     "absorb",
	'acudir':       "come, turn to",
	'admitir':      "admit, accept",
	'amar':         "love",
	'aprender':     "learn",
	'asistir':      "attend",
	'ayudar':       "help",
	'bailar':       "dance",
	'barrer':       "sweep",
	'beber':        "drink",
	'buscar':       "look for, seek",
	'caminar':      "walk",
	'cantar':       "sing",
	'ceder':        "yield",
	'cenar':        "have dinner",
	'charlar':      "chat",
	'clonar':       "clone",
	'cocinar':      "cook",
	'coincidir':    "coincide",
	'comer':        "eat",
	'cometer':      "commit",
	'compartir':    "share",
	'comprar':      "buy",
	'comprender':   "understand",
	'consistir':    "consist of",
	'contestar':    "answer",
	'correr':       "run",
	'cortar':       "cut",
	'coser':        "sew",
	'cumplir':      "carry out",
	'datar':        "date",
	'deber':        "owe, must",
	'decidir':      "decide",
	'declarar':     "declare",
	'definir':      "define",
	'desear':       "want, wish",
	'dibujar':      "draw",
	'discutir':     "argue, discuss",
	'distar':       "be away from",
	'distinguir':   "distinguish",
	'empinar':      "tip up, raise",
	'emprender':    "undertake",
	'encalar':      "whitewash",
	'enseñar':      "teach",
	'esconder':     "hide",
	'escuchar':     "listen",
	'esperar':      "wait for, hope",
	'esposar':      "handcuff",
	'estudiar':     "study",
	'evadir':       "evade",
	'exceder':      "exceed",
	'existir':      "exist",
	'formar':       "form",
	'ganar':        "win, earn",
	'gastar':       "spend",
	'glosar':       "gloss",
	'golpear':      "hit, punch",
	'grapar':       "staple",
	'gustar':       "be pleasing to",
	'hablar':       "speak",
	'helar':        "freeze, get cold",
	'hibernar':     "hibernate",
	'insistir':     "insist",
	'lamer':        "lick",
	'lavar':        "wash",
	'limpiar':      "clean",
	'llevar':       "take",
	'llorar':       "cry",
	'maltear':      "malt",
	'manar':        "drip with, flow",
	'meter':        "put",
	'mirar':        "look at",
	'nadar':        "swim",
	'necesitar':    "need",
	'nublar':       "cloud",
	'nutrir':       "nourish",
	'ocurrir':      "happen",
	'ofender':      "offend",
	'partir':       "cut, split",
	'penar':        "punish",
	'permitir':     "allow",
	'pintar':       "paint",
	'platicar':     "talk",
	'ponderar':     "praise, consider",
	'poseer':       "have",
	'procesar':     "prosecute, process",
	'prometer':     "promise",
	'quedar':       "stay",
	'rasar':        "skim",
	'recibir':      "receive, welcome",
	'regresar':     "return",
	'relampaguear': "flash lightning",
	'reprender':    "reprimand",
	'responder':    "answer, reply",
	'sacar':        "take out, remove",
	'seriar':       "mass-produce",
	'someter':      "submit, subdue",
	'subir':        "go up",
	'sufrir':       "suffer",
	'tejer':        "knit",
	'temer':        "fear",
	'tocar':        "touch",
	'tomar':        "drink, take",
	'trabajar':     "work",
	'trinchar':     "carve",
	'unir':         "join",
	'usar':         "use",
	'vender':       "sell",
	'viajar':       "travel",
	'visitar':      "visit",
	'vivir':        "live",
}

irregulars = {
	'abrazar':      ("hug", None, "fspt:abracé fspb:abrace sspb:abraces tspb:abrace fppb:abracemosa sppb:abracéis tppb:abracen"),
	'abrir':        ("open", None, "po:abierto"),
	'acordar':      ("agree", 'recordar', ""),
	'adquirir':     ("acquire, purchase", None, "fspr:adquiero sspr:adquieres tspr:adquiere tppr:adquieren fspb:adquiera sspb:adquieras tspb:adquiera tppb:adquieran"),
	'aducir':       ("adduce", 'conducir', ""),
	'amanecer':     ("dawn", 'conocer', ""),
	'andar':        ("walk", None, "fspt:anduve sspt:anduviste tspt:anduvo fppt:anduvimos sppt:anduvisteis tppt:anduvieron"),
	'anochecer':    ("get dark", 'conocer', ""),
	'argüir':       ("argue", None, "ge:arguyendo fspr:arguyo sspr:arguyes tspr:arguye tppr:arguyen tspt:arguyó tppt:arguyeron fspb:arguya sspb:arguyas tspb:arguya fppb:arguyamos sppb:arguyáis tppb:arguyan ssio:arguye"),
	'bullir':       ("boil", None, "ge:bullendo tspt:bulló tppt:bulleron"),
	'caber':        ("fit", None, "rf:cabr fspr:quepo fspt:cupe sspt:cupiste tspt:cupo fppt:cupimos sppt:cupisteis tppt:cupieron fspb:quepa sspb:quepas tspb:quepa fppb:quepa sppb:quepáis tppb:quepan"),
	'caer':         ("fall", None, "ge:cayendo po:caído fspr:caigo sspt:caíste tspt:cayó fppt:caímos sppt:caísteis tppt:cayeron fspb:caiga sspb:caigas tspb:caiga fppb:caigamos sppb:caigáis tppb:caigan"),
	'cazar':        ("hunt", None, "fspt:cacé fspb:cace sspb:caces tspb:cace fppb:cacemos sppb:cacéis tppb:cacen"),
	'colegir':      ("infer, deduce", 'elegir', ""),
	'componer':     ("compose", 'poner', "ssio:compón"),
	'concluir':     ("conclude", 'construir', ""),
	'conducir':     ("lead, drive", None, "fspr:conduzco fspt:conduje sspt:condujiste tspt:condujo fppt:condujimos sppt:condujisteis tppt:condujeron fspb:conduzca sspb:conduzcas tspb:conduzca fppb:conduzcamos sppb:conduzcáis tppb:conduzcan"),
	'conocer':      ("know, meet", None, "fspr:conozco fspb:conozca sspb:conozcas tspb:conozca fppb:conozcamos sppb:conozcáis tppb:conozcan"),
	'construir':    ("build", None, "ge:construyendo fspr:construyo sspr:construyes tspr:construye tppr:construyen tspt:construyó tppt:construyeron fspb:construya sspb:construyas tspb:construya fppb:construyamos sppb:construyáis tppb:construyan ssio:construye"),
	'coproducir':   ("co-produce", 'conducir', ""),
	'crecer':       ("grow", 'conocer', ""),
	'cubrir':       ("cover", None, "po:cubierto"),
	'dar':          ("give", None, "fspr:doy svpr:das sppr:dais fspt:di sspt:diste tspt:dio fppt:dimos sppt:disteis tppt:dieron fspb:dé tspb:dé sppb:deis svio:da"),
	'decir':        ("say", None, "rf:dir po:dicho ge:diciendo fspr:digo sspr:dices tspr:dice tppr:dicen fspt:dije sspt:dijiste tspt:dijo fppt:dijimos sppt:dijisteis tppt:dijeron fspb:diga sspb:digas tspb:diga fppb:digamos sppb:digáis tppb:digan ssio:di"),
	'deducir':      ("deduce", 'conducir', ""),
	'deshacer':     ("undo", 'hacer', ""),
	'dirigir':      ("manage, direct", None, "fspr:dirijo fspb:dirija sspb:dirijas tspb:dirija fppb:dirijamos sppb:dirijáis tppb:dirijan"),
	'discernir':    ("discern, distinguish", None, "fspr:discierno sspr:disciernes tspr:discierne tppr:disciernen fspb:discierna sspb:disciernas tspb:discierna tppb:disciernan ssio:discierne"),
	'disponer':     ("make available", 'poner', ""),
	'distraer':     ("distract", 'traer', ""),
	'dormir':       ("sleep", None, "ge:durmiendo fspr:duermo sspr:duermes tspr:duerme tppr:duermen tspt:durmió tppt:durmieron fspb:duerma sspb:duermas tspb:duerma fppb:durmamos sppb:durmáis tppb:duerman ssio:duerme"),
	'elegir':       ("choose", None, "ge:eligiendo fspr:elijo sspr:eliges tspr:elige tppr:eligen tspt:eligió tppt:eligieron fspb:elija sspb:elijas tspb:elija fppb:elijamos sppb:elijáis tppb:elijan ssio:elige"),
	'escoger':      ("choose", None, "fspr:escojo fspb:escoja sspb:escojas tspb:escoja fppb:escojamos sppb:escojáis tppb:escojan"),
	'escribir':     ("write", None, "po:escrito"),
	'estar':        ("be", None, "fspr:estoy sspr:estás tspr:está tppr:están fspt:estuve sspt:estuviste tspt:estuvo fppt:estuvimos sppt:estuvisteis tppt:estuvieron fspb:esté sspb:estés tspb:esté tppb:estén ssio:está"),
	'exigir':       ("demand", 'dirigir', ""),
	'extinguir':    ("extinguish", None, "fspr:extingo fspb:extinga sspb:extingas tspb:extinga fppb:extingamos sppb:extingáis tppb:extingan"),
	'freír':        ("fry", 'reír', "po:frito"),
	'granizar':     ("hail", 'cazar', ""),
	'haber':        ("have (aux.)", None, "rf:habr fspr:he sspr:has svpr:has tspr:ha fppr:hemos tppr:han fspt:hube sspt:hubiste tspt:hubo fppt:hubimos sppt:hubisteis tppt:hubieron fspb:haya sspb:hayas tspb:haya fppb:hayamos sppb:hayáis tppb:hayan"),
	'hacer':        ("do, make", None, "rf:har po:hecho fspr:hago fspt:hice sspt:hiciste tspt:hizo fppt:hicimos sppt:hicisteis tppt:hicieron fspb:haga sspb:hagas tspb:haga fppb:hagamos sppb:hagáis tppb:hagan ssio:haz"),
	'hervir':       ("boil", None, "ge:hirviendo fspr:hiervo sspr:hierves tspr:hierve tppr:hierven tspt:hirvió tppt:hirvieron fspb:hierva sspb:hiervas tspb:hierva fppb:hirvamos sppb:hirváis tppb:hiervan ssio:hierve"),
	'huir':         ("flee", 'construir', ""),
	'inducir':      ("induce", 'conducir', ""),
	'introducir':   ("insert", 'conducir', ""),
	'ir':           ("go", None, "ge:yendo fspr:voy sspr:vas svpr:vas tspr:va fppr:vamos sppr:vais tppr:van fspt:fui sspt:fuiste tspt:fue fppt:fuimos sppt:fuisteis tppt:fueron fsii:iba ssii:ibas svii:ibas tsii:iba fpii:íbamos spii:ibais tpii:iban fspb:vaya sspb:vayas tspb:vaya fppb:vayamos sppb:vayáis tppb:vayan ssio:ve svio:andá"),
	'jugar':        ("play", None, "fspr:juego sspr:juegas tspr:juega tppr:juegan fspt:jugué fspb:juegue sspb:juegues tspb:juegue fppb:juguemos sppb:juguéis tppb:jueguen ssio:juegua"),
	'leer':         ("read", None, "po:leído ge:leyendo"),
	'llegar':       ("arrive, come", None, "fspt:llegué fspb:llegue sspb:llegues tspb:llegue fppb:lleguemos sppb:lleguéis tppb:lleguen"),
	'llover':       ("rain", 'mover', ""),
	'lucir':        ("shine, wear", None, "fspr:luzco fspb:luzca sspb:luzcas tspb:luzca fppb:luzcamos sppb:luzcáis tppb:luzcan"),
	'medir':        ("measure", 'pedir', ""),
	'morder':       ("bite", None, "fspr:muerdo sspr:muerdes tspr:muerde tppr:muerden fspb:muerda sspb:muerdas tspb:muerda tppb:muerdan"),
	'morir':        ("die", None, "po:muerto ge:muriendo fspr:muero sspr:mueres tspr:muere tppr:mueren tspt:murió tppt:murieron fspb:muera sspb:mueras tspb:muera fppb:muramos sppb:muráis tppb:mueran ssio:muere"),
	'mostrar':      ("show", None, "fspr:muestro sspr:muestras tspr:muestra tppr:muestran fspb:muestre sspb:muestres tspb:muestre tppb:muestren ssio:muestra"),
	'mover':        ("move", None, "fspr:muevo sspr:mueves tspr:mueve tppr:mueven fspb:mueva sspb:muevas tspb:mueva tppb:muevan ssio:mueve"),
	'nevar':        ("snow", None, "tspr:nieva tspb:nieve ssio:nieva"),
	'obtener':      ("obtain, get", 'tener', "ssio:obtén"),
	'oír':          ("hear, listen", None, "ge:oyendo po:oído rf:oir fspr:oigo sspr:oyes tspr:oye fppr:oímos tppr:oyen sspt:oíste tspt:oyó fppt:oímos sppt:oísteis tppt:oyeron fspb:oiga sspb:oigas tspb:oiga fppb:oigamos sppb:oigáis tppb:oigan ssio:oye"),
	'pagar':        ("pay", None, "fspt:pagué fspb:pague sspb:pagues tspb:pague fppb:paguemos sppb:paguéis tppb:paguen"),
	'pedir':        ("ask for, order", None, "ge:pidiendo fspr:pido sspr:pides tspr:pide tppr:piden tspt:pidió tppt:pidieron fspb:pida sspb:pidas tspb:pida fppb:pidamos sppb:pidáis tppb:pidan ssio:pide"),
	'pensar':       ("think", None, "fspr:pienso sspr:piensas tspr:piensa tppr:piensan fspb:piense sspb:pienses tspb:piense tppb:piensen ssio:piensa"),
	'perder':       ("lose", None, "fspr:pierdo sspr:pierdes tspr:pierde tppr:pierden fspb:pierda sspb:pierdas tspb:pierda tppb:pierdan ssio:pierde"),
	'poder':        ("can", None, "rf:podr ge:pudiendo fspr:puedo sspr:puedes tspr:puede tppr:pueden fspt:pude sspt:pudiste tspt:pudo fppt:pudimos sppt:pudisteis tppt:pudieron fspb:pueda sspb:puedas tspb:pueda tppb:puedan ssio:puede"),
	'poner':        ("put", None, "rf:pondr po:puesto fspr:pongo fspt:puse sspt:pusiste tspt:puso fppt:pusimos sppt:pusisteis tppt:pusieron fspb:ponga sspb:pongas tspb:ponga fppb:pongamos sppb:pongáis tppb:pongan ssio:pon"),
	'promover':     ("promote", 'mover', ""),
	'proponer':     ("propose", 'poner', ""),
	'pudrir':       ("rot, putrefy", None, "po:podrido"),
	'querer':       ("want, love", None, "rf:querr fspr:quiero sspr:quieres tspr:quiere tppr:quieren fspt:quise sspt:quisiste tspt:quiso fppt:quisimos sppt:quisisteis tppt:quisieron fspb:quiera sspb:quieras tspb:quiera tppb:quieran ssio:quiere"),
	'recoger':      ("pick up, gather", 'escoger', ""),
	'reconducir':   ("redirect", 'conducir', ""),
	'reconocer':    ("recognize", 'conocer', ""),
	'recordar':     ("remember", None, "fspr:recuerdo sspr:recuerdas tspr:recuerda tppr:recuerdan fspb:recuerde sspb:recuerdes tspb:recuerde tppb:recuerden ssio:recuerda"),
	'rehacer':      ("redo", 'hacer', ""),
	'reponer':      ("put back", 'poner', ""),
	'reproducir':   ("reproduce", 'conducir', ""),
	'resolver':     ("solve", None, "po:resuelto fspr:resuelvo sspr:resuelves tspr:resuelve tppr:resuelven fspb:resuelva sspb:resuelvas tspb:resuelva tppb:resuelvan ssio:resuelve"),
	'reír':         ("laugh", None, "ge:riendo fspr:río sspr:ríes tspr:ríe fppr:reímos tppr:ríen sspt:reíste tspt:rió fppt:reímos sppt:reísteis tppt:rieron fspb:ría sspb:rías tspb:ría fppb:ríamos sppb:riais tppb:rían ssio:ríe"),
	'roer':         ("gnaw on", 'caer', ""),
	'romper':       ("break", None, "po:roto"),
	'saber':        ("know", None, "rf:sabr fspr:sé fspt:supe sspt:supiste tspt:supo fppt:supimos sppt:supisteis tppt:supieron fspb:sepa sspb:sepas tspb:sepa fppb:sepamos sppb:sepáis tppb:sepan"),
	'salir':        ("leave, go out", None, "rf:saldr fspr:salgo fspb:salga sspb:salgas tspb:salga fppb:salgamos sppb:salgáis tppb:salga ssio:sal"),
	'seducir':      ("seduce", 'conducir', ""),
	'sentar':       ("sit", None, "fspr:siento sspr:sientas tspr:sienta tppr:sientan fspb:siente sspb:sientes tspb:siente tppb:sienten ssio:sienta"),
	'sentir':       ("feel", None, "ge:sintiendo fspr:siento sspr:sientes tspr:siente tppr:sienten tspt:sintió tppt:sintieron fspb:sienta sspb:sientas tspb:sienta fppb:sintamos sppb:sintáis tppb:sientan ssio:siente"),
	'ser':          ("be", None, "fspr:soy sspr:eres svpr:sos tspr:es fppr:somos sppr:sois tppr:son fspt:fui sspt:fuiste tspt:fue fppt:fuimos sppt:fuisteis tppt:fueron fsii:era ssii:eras tsii:era fpii:éramos spii:erais tpii:eran fspb:sea sspb:seas tspb:sea fppb:seamos sppb:seáis tppb:sean ssio:sé"),
	'suponer':      ("suppose", 'poner', ""),
	'tañer':        ("strum", None, "ge:tañendo tspt:tañó tppt:tañeron"),
	'tener':        ("have, be", None, "rf:tendr fspr:tengo sspr:tienes tspr:tiene tppr:tienen fspt:tuve sspt:tuviste tspt:tuvo fppt:tuvimos sppt:tuvisteis tppt:tuvieron fspb:tenga sspb:tengas tspb:tenga fppb:tengamos sppb:tengáis tppb:tengan ssio:ten"),
	'traducir':     ("translate", 'conducir', ""),
	'traer':        ("bring", None, "ge:trayendo fspr:traigo fspt:traje sspt:trajiste tspt:trajo fppt:trajimos sppt:trajisteis tppt:trajeron fspb:traiga sspb:traigas tspb:traiga fppb:traigamos sppb:traigáis tppb:traigan"),
	'tronar':       ("thunder", None, "tspr:truena tspb:truene ssio:truena"),
	'valer':        ("be worth, cost", None, "rf:valdr fspr:valgo fspb:valga sspb:valgas tspb:valga fppb:valgamos sppb:valgáis tppb:valga"),
	'venir':        ("come, arrive", None, "rf:vendr fspr:vengo sspr:vienes tspr:viene tppr:vienen fspt:vine sspt:viniste tspt:vino fppt:vinimos sppt:vinisteis tppt:vinieron fspb:venga sspb:vengas tspb:venga fppb:vengamos sppb:vengáis tppb:vengan ssio:ven"),
	'ver':          ("see", None, "po:visto fspr:veo sppr:veis fspt:vi tspt:vio fsii:veía ssii:veías tsii:veía fpii:veíamos spii:veíais tpii:veían fspb:vea sspb:veas tspb:vea fppb:veamos sppb:veáis tppb:vean"),
	'volver':       ("return", 'resolver', ""),
}
